# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# bufferClipArea.py
# Created on: 2014-08-15 10:54:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
arcpy.env.workspace = "J:\Users\juliana\Documents\RESULTADOS_DOUTORADO\Paisagens_Modelos_Smmal_Mammals\Targets_Final\Targets_VALUE_Final\Tabela_SourceTargets"

mosaic_reclass = "F:\\data\\Juliana_inpe\\mosaic_reclass.shp"

rasterList = arcpy.ListRasters()
fcList=arcpy.ListFeatureClasses ()
mosaic_reclass =fcList[0]



# Process: Raster to Polygon


for i in rasterList:
    arcpy.RasterToPolygon_conversion(i, i+'_800m_shp', "SIMPLIFY", "VALUE")
    arcpy.Buffer_analysis(i+'_800m_shp', i+'_shp_buffer_800m', "800 Meters", "FULL", "ROUND", "ALL", "")
    ofile2=unicode(""+os.path.splitext(mosaic_reclass)[0]+'_'+i+'_shp_buffer_800m.shp')
    
    ofile3=unicode(""+os.path.splitext(mosaic_reclass)[0]+'_'+i+'_shp_buffer_800m_AreHA')
    
    #arcpy.Clip_analysis(mosaic_reclass, i+'_shp_buffer_800m', ofile2, "")
    arcpy.Clip_analysis("mosaic_reclass",i+'_shp_buffer_800m',ofile2,"")
    arcpy.CalculateAreas_stats(ofile2, ofile3)
    arcpy.AddField_management(ofile3, 'areaHA', "DOUBLE", 20, 20)
    arcpy.AddField_management(ofile3, 'PCT', "DOUBLE", 20, 20)
    arcpy.AddField_management(ofile3, 'SUMARY', "DOUBLE", 20, 20)
    
    arcpy.CalculateField_management(ofile3,"areaHA",'!F_AREA!/10000',"PYTHON")
    
   
            
            
    ofile4=unicode(""+os.path.splitext(i)[0]+'_TXT_800.txt')       
    summed_total =0   
    with arcpy.da.SearchCursor(ofile3, "areaHA") as cursor:
        for row in cursor:
            summed_total = summed_total + row[0] 
            expressao='!areaHA!/'+`summed_total`+'*100'
        arcpy.CalculateField_management(ofile3,"PCT",expressao,"PYTHON")
        
        arcpy.SelectLayerByAttribute_management(ofile3,"NEW_SELECTION",'"GRIDCODE"=10 or "GRIDCODE"=11 or "GRIDCODE"=12 ')
        arcpy.Statistics_analysis (ofile3, ofile4, [["PCT", "sum"]])
                    
    
    

