# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# intersect_arcpy.py
# Created on: 2015-05-30 11:15:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Arquivo_acumula_poligonos = "Arquivo_acumula_poligonos"
Arquivo_acumula_poligonos_In = "C:\\Users\\Marcos\\Documents\\ArcGIS\\Default.gdb\\Arquivo_acumula_poligonos_In"

# Process: Intersect
arcpy.Intersect_analysis("Arquivo_acumula_poligonos #", Arquivo_acumula_poligonos_In, "ONLY_FID", "", "INPUT")

